name: Build and Release

on:
  push:
    tags:
      - "v*"
jobs:
  ship:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
      - name: install packages
        run: yarn install
      - name: Build
        run: yarn build
      - name: release - pack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn pack
      - name: Get release tag from git revision
        run: |
          GITHUB_TAG=$(cat package.json | jq -r '.version')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cray-lens-cray-${{ env.GITHUB_TAG }}.tgz
          prerelease: true